### ISSUE TITLE
Can this package used for gene expression data?

### ISSUE THREAD

**Issue by wang950312** [sjczheng/EpiDISH#1]
If I define ref.m be the CIBERSORT LM22 matrix, and beta.m be input gene expression data, does the result be right when select the CBS method?

**Comment by sjczheng** [comment]
Yes. It dose.

**Comment by phoang1012** [comment]
Hi,
The potential application of the algorithm in expression is interesting. In such case, would you say the appropriate input be normalized CPM (with some modifications of the code) or it has to be normalized to 0-1 like beta values or otherwise?
Thanks!

**Comment by sjczheng** [comment]
Hi,

Theoretically, the statistical model should work in expression data.
However, the performance might be different and needs to be evaluated.
The DNA methylation, especially the array data, is special as the methylation value is the ratio of methylated and unmethylated signals. In this sense, methylation data is self-normalized. This internal normalization removes some of the technical variability. Therefore, I think that using the DNAm data to estimate cell-type fractions is easier and more accurate than using the expression data. 
You could just use CPM as input or normalize CPM to 0-1. But neither of them could remove as much technical variability as the DNAm data. Since the variability is higher, you have less power.
There is no doubt you can detect some differentially expressed genes in some cell types if the effect size is big enough.
But like I said, it needs to be benchmarked in expression data before we could define the appropriate input.

Best,
Shijie
