### ISSUE TITLE
Estimates of the effects = 1.00 / -1.00

### ISSUE THREAD

**Issue by antgiord** [sjczheng/EpiDISH#10]
Hello.
I'm using CellDMC to estimate cell-specific differential methylation based on a phenotype (=SNPs) that can be 0/1/2.
Some phenotypes will have values of 0, 1 and 2 (phenotype handled by CellDMC as continuous), while others will only be 0 and 1 (phenotype handled as binary).
My cell matrix is an extract of Houseman's whole blood matrix (I use: CD8, CD4, B cells, NK, Neutrophils and Monocytes). 

For many of my significant DMCTs I get an estimate of -1.00 or +1.00.
Here a short example:

> celldmc.o$coe$NK
                          Estimate        SE               t                 p                       adjP
cg21315684 1.0000000 0.4916815 3.5004512 0.0005185787 0.002074315
cg11048520 1.0000000 1.0725766 1.0101717 0.3130442175 0.417392290
cg25076062 0.5064478 0.4858288 1.0424409 0.2978580539 0.417392290
cg21463449 0.3882528 0.4984584 0.7789072 0.4365103747 0.436510375

My questions are: 
- I understand this refers to beta-values, which are comprised between 0 and 1 by definition, but how to interpret those values? 
- Is there any way to avoid this approximation to 1 / -1 and get actual estimates? 

Thanks!

**Comment by sjczheng** [comment]
Hi,

The estimated value is the estimated slope of the fitted regression model.
You could visualize this line from lm(y_ ~ phenotype:cell_type_fraction)
with y_ as the residual from lm(beta ~ cell_type_fraction). (i.e., y_ is
the cell type fraction adjusted beta values.)
Since you are using an ordinal variable, the estimated slope and associated
p values tell you whether the phenotype is associated with beta values. It
might be difficult to tell exactly what the estimated slope represents in
this scenario. If you have an additive effect from 0 to 1 to 2, and the
effects are the same, the estimated slope could represent estimated
difference between 0 and 1 or 1 and 2.
I assume you are interested in the estimated difference between two groups,
such as 0 vs. 1 or 1 vs. 2.
You could do separate analyses by submitting your data and treat them as 0
and 1.

Best,
Shijie
