### ISSUE TITLE
CellDMC issue

### ISSUE THREAD

**Issue by BastiDucreux** [sjczheng/EpiDISH#7]
Hi,
I have an issue regarding CellDMC function. I am currently applying it to my dataset but have this error.

```
celldmc.o <- CellDMC(beta.m, pheno.v, frac.m)
Binary phenotype detected. Predicted change will be 1 - 0.
Error in summary(Int.o)$coe[IntNames.v, ] : subscript out of bounds
```

I looked at the source code and it seems there is a problem with IntNames.v but can't understand it.
```
IntNames.v
[1] "EpiPheno"    "FibPheno"    "BPheno"      "NKPheno"     "CD4TPheno"   "CD8TPheno"   "MonoPheno"   "NeutroPheno" "EosinoPheno"

```
```
summary(Int.o)$coe
                  Estimate Std. Error       t value   Pr(>|t|)
(Intercept)   -3.199738026  3.5209962 -0.9087592981 0.37027101
frac.mEpi      4.086891922  3.5290549  1.1580698036 0.25540601
frac.mFib      5.380570314  3.8462666  1.3989072680 0.17145904
frac.mB        3.408837068  3.6231479  0.9408495418 0.35383062
frac.mNK       3.681033941  3.6322546  1.0134295012 0.31845681
frac.mCD4T     5.780981690  3.6966465  1.5638448867 0.12769073
frac.mCD8T     8.328347280  5.4847928  1.5184433659 0.13872168
frac.mMono     4.271271297  3.4865781  1.2250611231 0.22949345
frac.mNeutro   4.086622747  3.5310449  1.1573409099 0.25569923
EpiPheno       0.071547749  0.0494422  1.4470987764 0.15759528
BPheno        -4.792213652  4.2030943 -1.1401632376 0.26268052
NKPheno        4.395854796  4.8555005  0.9053350595 0.37205422
CD4TPheno     -2.295273335  4.4982204 -0.5102625359 0.61336946
MonoPheno     -0.001726174  2.0475597 -0.0008430395 0.99933259
NeutroPheno    0.132065586  0.8000836  0.1650647337 0.86993138
EosinoPheno  -28.860272561 15.7205145 -1.8358351201 0.07568965


```
It seems FibPheno and CD8TPheno have disappeared and this is why subscript is out of bounds.
Thanks in advance for your help.

**Comment by dsaha0295** [comment]
Also having the same issue, any updates?

**Comment by BastiDucreux** [comment]
It still doesn't work for my part but I don't get the error message anymore, the function runs just without ending after saying "Binary phenotype detected. Predicted change will be 1 - 0."

**Comment by sjczheng** [comment]
Hi. Sorry. I just see this.
Could you send me a subset of your data (3 CpGs or so) to my email (shijieczheng@gmail.com),  so I can test it?
Thanks so much.

**Comment by sjczheng** [comment]
Hi Bastien,
I looked at your data. And the error comes from the unfitness.You could check the Rank of the design matrix by design <- model.matrix(~ frac.m + pheno.v:frac.m)[, -1]
> Matrix::rankMatrix(design)
[1] 16
attr(,"method")
[1] "tolNorm2"
attr(,"useGrad")
[1] FALSE
attr(,"tol")
[1] 1.065814e-14
> dim(design)
[1] 48 18

As you see, the design matrix contains column vectors 0 or parallel to other column vectors. In this case, the linear model with not include those columns.Specifically in your data,> which(colSums(design) == 0)
 frac.mFib:pheno.vCTRL frac.mCD8T:pheno.vCTRL 
                    11                     15 
> sum(frac.m[pheno.v == "CTRL", "CD8T"])
[1] 0
> sum(frac.m[pheno.v == "CTRL", "Fib"])
[1] 0

As you see, the fractions of fibroblasts and CD8T cells are exactly all 0 for control groups. Without any variation, we couldn't make any statistical inference on them. This could happen when your sample size is small. In your case, 12 is quite small for EWAS. You could either decrease your resolution. For example, instead of using the fractions of immune cells, you use the total fractions of immune cells (Epi, Fib, IC). You could also consider removing Fib when estimating the fractions as the fractions of FIb are quite small in your data. Or you need to increase your sample size. 
Besides, in the linear model, including more variables will increase the variability of the model. As your sample size is quite small (n=12), making high-resolution inferences of 9 cell types might be underpowered. I highly recommend you reconsider this. Not just for CellDMC, for any statistical model, you will always face the sample size power issue.
I will update the CellDMC function with an error message. Thanks for your question.
Best, 
Shijie

**Comment by BastiDucreux** [comment]
Thank you for these very clear explanation ! I will certainly take these considerations into account.
