### ISSUE TITLE
Appropriate input for CellDMC?

### ISSUE THREAD

**Issue by phoang1012** [sjczheng/EpiDISH#8]
Hello,
I used Combat to correct for batch effects on the methylation data. From reading the Methods, it seems that the input beta values were normalized but not batch corrected. I wonder if you could confirm if this is correct?
 
I tested the algorithm using two different approaches:
1. Using methylation beta corrected and adjusted by Combat for technical factors
2. Using methylation beta normalized by BIMQ, but not batch corrected by Combat. Instead, I used cov.mod option in CellDMC to specify these batch covariates.
 
I got a lot more (almost double) the number of probes identified as differentially methylated by approach 1.  Most differentially methylated probes in approach 2 are also included in 1, but not all. Could you please share some insights which approach would be the most appropriate for using CellDMC? 

Thank you!

**Comment by sjczheng** [comment]
Hi @phoang1012 

Thanks for your interest in CellDMC.

"From reading the Methods, it seems that the input beta values were normalized but not batch corrected. I wonder if you could confirm if this is correct?"
EpiDISH/CellDMC does not directly correct any batch effects. There are two approaches to correct the batch effect when running CellDMC (just like what you did). 1: Feed CellDMC batch corrected beta values; 2: Include batches as covariates. Your case should be the first one.

The difference is caused by ComBat, which uses the empirical bayes framework. Personally, I think using ComBat is better. 

To me, if I confirm that there are batch effects in your data (such as the correlation between top PCs and batches), I tend to use ComBat on M values (transformed from beta values), transform M values back to beta values, and feed CellDMC with corrected beta values.

Best,
Shijie
